version: "3.3"

networks:
  autoheal:
    name: autoheal

services:

  autoheal:
    container_name: autoheal
    image: l33tlamer/docker-autoheal:latest
    restart: unless-stopped
    networks:
      - autoheal
    environment:
      - "DOCKER_SOCK=tcp://docker-socket-proxy:2375"
      - "NTFY_URL=http://192.168.20.50:8113/autoheal"
      - "NTFY_TOKEN=ABCD"
      - "NTFY_TITLE=Autoheal @ Raspberry Basement"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  docker-socket-proxy:
    container_name: docker-socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    networks:
      - autoheal
    ports:
      - 127.0.0.1:2375:2375
    environment:
      - "SOCKET_PATH=/var/run/docker.sock"
      - "POST=1"         # read/write access (required for autoheal)
      - "CONTAINERS=1"   # Allow access to containers (required for autoheal)
      - "EVENTS=0"       # Granted by default but not required for autoheal
      - "PING=0"         # Granted by default but not required for autoheal
      - "VERSION=0"      # Granted by default but not required for autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
